// Single source of truth for NAP, hours, insurance wording, and links.
export const BIZ = {
  name: "Meadowlands Commercial Door Solutions",
  legalName: "Meadowlands Commercial Door Solutions",
  shortName: "MCDS",
  tagline: "Commercial overhead, rolling steel, dock, and entrance door systems — Jersey City & North Jersey",
  phone: "",
  phoneE164: "",
  phoneHref: "/quote",
  smsHref: "/quote",
  email: "info@meadowlandscommercialdoorsolutions.com",
  emailHref: "mailto:info@meadowlandscommercialdoorsolutions.com",
  quotesEmail: "quotes@meadowlandscommercialdoorsolutions.com",
  quoteNotifyEmails: ["bar.izhaki@gmail.com"],
  licenseId: "Insured",
  bsis: "Insured",
  url: "https://meadowlandscommercialdoorsolutions.com",
  address: {
    street: "333 Washington St",
    locality: "Jersey City",
    region: "NJ",
    postalCode: "07302",
    country: "US",
    full: "333 Washington St, Jersey City, NJ 07302",
  },
  geo: { lat: 40.7178, lng: -74.0435 },
  metroBounds: {
    minLat: 40.62,
    maxLat: 40.96,
    minLng: -74.26,
    maxLng: -73.93,
  },
  metroMap: { lat: 40.76, lng: -74.06, zoom: 10 },
  region: "Jersey City, Hudson County & the Meadowlands",
  regionShort: "Jersey City & North Jersey",
  metroLabel: "North Jersey & NYC waterfront",
  hoursLabel: "Mon–Fri 7–6 · Sat 8–2",
  hours247: false,
  emergencyNote: "Priority commercial dispatch during posted hours",
  heroPhoto: "/photos/branding-generated--hero-meadowlands.webp",
  mapPhoto: "/photos/branding-generated--service-map.webp",
  hours: [
    { day: 0, open: "00:00", close: "00:00", label: "Sunday", closed: true },
    { day: 1, open: "07:00", close: "18:00", label: "Monday" },
    { day: 2, open: "07:00", close: "18:00", label: "Tuesday" },
    { day: 3, open: "07:00", close: "18:00", label: "Wednesday" },
    { day: 4, open: "07:00", close: "18:00", label: "Thursday" },
    { day: 5, open: "07:00", close: "18:00", label: "Friday" },
    { day: 6, open: "08:00", close: "14:00", label: "Saturday" },
  ] as const,
  social: {
    google: "",
    yelp: "",
    facebook: "",
    instagram: "",
    tiktok: "",
  },
};

export const hasPhone = Boolean(BIZ.phone && BIZ.phoneE164);
